{{- range .Values.pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
  labels:
    {{- include "backend.labels" $ | nindent 4 }}
    {{- with $.Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
  {{- if .selector }}
  selector:
    {{- toYaml .selector | nindent 4 }}
  {{- end }}
  {{- if .volumeMode }}
  volumeMode: {{ .volumeMode }}
  {{- end }}
{{- end }}
