apiVersion: v2
name: lido-backend
description: Lido backend application Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/lidofinance/lido-local-devnet
keywords:
  - lido
  - backend
  - application
kubeVersion: '>=1.19.0-0'
maintainers:
  - name: Lido Team
    url: https://lido.fi
