apiVersion: v2
name: lido-council
description: Lido Council Daemon Helm chart
type: application
version: 1.0.0
appVersion: "2.5.2"
kubeVersion: '>=1.19.0-0'
dependencies:
  - name: "lido-app"
    version: "1.0.1"
    repository: "file://../lido-app"
