apiVersion: v2
name: lido-docker-registry
description: Lido Docker Registry for Devnets
type: application
version: 0.1.0
appVersion: "2.5.2"
kubeVersion: '>=1.19.0-0'
dependencies:
- name: "docker-registry-ui"
  version: "1.1.3-patched"
  repository: "file://../../vendor/docker-registry-ui"
